apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector: 
    app: prometheus
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: prometheus
  - name: pushgateway
    protocol: TCP
    port: 9091
    targetPort: pushgateway
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus-adapter
  ports:
  - name: api
    protocol: TCP
    port: 443
    targetPort: https

