---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender-external
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender-external
  template:
    metadata:
      labels:
        app: vpa-recommender-external
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: recommender-external
          image: k8s.gcr.io/autoscaling/vpa-recommender-external:0.12.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
          ports:
            - name: prometheus
              containerPort: 8942
