FROM registry.ddbuild.io/images/mirror/golang:1.19 as builder

ENV GO111MODULE "on"
ENV GOPATH=/go
ENV CGO_ENABLED=0

WORKDIR /go/src/k8s.io/autoscaler/vertical-pod-autoscaler
COPY . /go/src/k8s.io/autoscaler/vertical-pod-autoscaler
WORKDIR /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender

RUN env CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o vpa-recommender --ldflags "-s"

FROM 486234852809.dkr.ecr.us-east-1.amazonaws.com/base:focal

COPY --from=builder /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/vpa-recommender /usr/local/bin/vpa-recommender
